# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 13:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20181004_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
